### ISSUE TITLE
How to install avahi-gobject

### ISSUE THREAD

**Issue by Suzie97** [syfds/soundy#22]
While trying to compile from source, an error is displyed stating `depedency avahi-gobject not found`.

I did `sudo apt-get install libavahi-gobject0` and it still doesn't compile.

**Comment by syfds** [comment]
hi @Suzie97 , you need this one: libavahi-gobject-dev

so try `sudo apt-get install libavahi-gobject-dev` and tell if it worked for you!

**Comment by Suzie97** [comment]
Thanks, it works now 👍️
