### ISSUE TITLE
Using rounded window corners and a flat headerbar

### ISSUE THREAD

**Issue by Suzie97** [syfds/soundy#23]
I think, adding rounded window corners and making the headerbar flat and merge with the window, like planner makes the application look more modern.

**Comment by Suzie97** [comment]
![Screenshot from 2021-05-14 00-03-05](https://user-images.githubusercontent.com/68198116/118170513-cd998480-b447-11eb-9f68-7e260abc850e.png)

This is how it looks like.

**Comment by syfds** [comment]
hi @Suzie97 , thank you for your PR! I would like to keep the standard behavior for the header and bottom corners to be more consistent to other standard elementary apps. Now the headerbar contains quite a lot of ui elements and I think it can be confusing for end user if there is no separator.

**Comment by Suzie97** [comment]
Rounded corners will be the standard in elementary OS 6. So it might be better to implement that.

**Comment by Suzie97** [comment]
I understand your concerns about the headerbar's UI elements. What do you think about implementing them in the main window instead of the headerbar?

**Comment by syfds** [comment]
hi @Suzie97, you are right concerning rounded corners and elementary 6! Could you please make a PR only with rounded corners? I would keep the header bar for now like it is.

**Comment by Suzie97** [comment]
I've updated the existing pull request. You can merge it.

**Comment by syfds** [comment]
I wrote a comment in your PR, can you take a look at it? Probably we can use the constant for rounded corners?

**Comment by Suzie97** [comment]
I can't see it in the comments of my PR. Am I looking in the right place?? Where can I find your comment?😅️

**Comment by syfds** [comment]
can you see my comment in https://github.com/syfds/soundy/pull/24/files? I mentioned you in the comment :-)

**Comment by Suzie97** [comment]
Should this issue be closed or the headerbar will be discussed further?

**Comment by syfds** [comment]
I would close this issue and create a new one for the headerbar or other ideas of redesign. What do you think about it?

**Comment by Suzie97** [comment]
How about opening a discussions page?? I think it would be more appropriate. Once we decide to implement something in discussions, we can open an issue to keep track of it.

**Comment by syfds** [comment]
I've added discussion feature to the repo, so feel free to start one and make suggestions ;-)

**Comment by syfds** [comment]
@Suzie97 , do you have a SoundTouch speaker?

**Comment by Suzie97** [comment]
I'm trying to find one. But Bose has stopped selling them in India anymore. Buying from third parties is super costly.

**Comment by syfds** [comment]
@Suzie97 , unfortunately Bose stopped to sell the SoundTouch speakers generally :-/ I thought about writing some small simulation of a speaker so Soundy is testable without a speaker 🤔

**Comment by Suzie97** [comment]
> @Suzie97 , unfortunately Bose stopped to sell the SoundTouch speakers generally :-/ I thought about writing some small simulation of a speaker so Soundy is testable without a speaker thinkingThat would be great.

 Also, I think Bose is working on providing more public API for their products. Maybe soundy can provide support for other bose products once the API is released.
