### ISSUE TITLE
Feature request: play URL

### ISSUE THREAD

**Issue by elChorche** [syfds/soundy#25]
Hi @syfds 
Here's an idea that might improve soundy: being able to play an internet radio stream that is not a preset. This is possible using the "/speaker" endpoint for sending an URL to a speaker. It would require an app-key though, maybe as an optional configuration option.
Keep up the good work & thanks a lot!

**Comment by syfds** [comment]
hi @elChorche , thank you for this idea! I took a look at the documentation and Bose doesn't recommend to play audio of longer duration than 15 seconds. Here a quote from Bose documentation: 

> Audio Notification UX Guidelines
> When developing an application that uses Audio Notifications, there are some important UX guidelines you should follow to ensure a great experience for your user. This page summarizes those guidelines.
> 
> Notification Brevity
> The Audio Notification API (aka the /speaker endpoint) is today primarily designed and intended for use with short (~1-15 second) notifications. Applications should only enable use cases aligned with this intent. There is no hard cap on Notification length, but Applications with primary use cases that commonly stretch beyond 20-30 seconds may not be approved in the Works with Bose certification process. Bose explicitly will not certify any Application that uses the API as an alternative mechanism for music playback.
> 

As workaround I think about the possibility to implement the functionaly to turn on bluetooth on and connect to the pc so you are able to play everything your pc can play. This approach has its restrictions so it is not the same as sending a URL to play to the speaker :-/

On the other hand this can be some nice feature for a alarm or similar.

**Comment by elChorche** [comment]
Thanks for looking into it. I know that the /speaker endpoint is intended for short notifications, but for me it works fine also using it with radio streams. But it is also only working on ST 10, 20, 30 and not on the Wave Music System or the link adapter, so it might not be the best idea. The bluetooth feature seems nice though :)

**Comment by syfds** [comment]
hi @elChorche , I'm currently seeking for tester for 0.3.0. So if you have some time and more than two SoundTouch speaker it would be cool if you could test the newest version with multiroom support. You can take the latest 0.3.* from https://github.com/syfds/soundy/releases.
