### ISSUE TITLE
Change required for AppCenter: No UI if no speaker is found

### ISSUE THREAD

**Issue by cassidyjames** [syfds/soundy#3]
Thanks for submitting your app to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Your app does not open a window or provide any feedback when a speaker is not found on the local network. As stated in the [AppCenter Publishing Requirements](https://docs.elementary.io/develop/appcenter/publishing-requirements#launching), your app should display its own graphical user interface on launch. In the case of an error, it should provide graphical feedback in an app window.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by cassidyjames** [comment]
Hm, after trying again, it did open. But it seems to not be reliably opening an app window, which should be resolved.

**Comment by syfds** [comment]
Hi @cassidyjames , thank you for your feedback!

**Comment by syfds** [comment]
hi @cassidyjames ,

now the whole window will open in case the speaker cannot be found in the local network. Here are some screenshots:

![image](https://user-images.githubusercontent.com/65869270/114297740-b7984d00-9ab2-11eb-9d73-f611e9edeae5.png)
![image](https://user-images.githubusercontent.com/65869270/114297746-c979f000-9ab2-11eb-931d-71b8268c706f.png)

Do you think this fix would be enough to meet the [Launching](https://docs.elementary.io/develop/appcenter/publishing-requirements#launching ) requirement?

**Comment by syfds** [comment]
I've created a new release https://github.com/syfds/soundy/releases/tag/v0.1.4 and submitted it in Appcenter Dashboard.

**Comment by cassidyjames** [comment]
@syfds this seems to work better, thanks for tackling it!
