### ISSUE TITLE
Add drop shadow to song art

### ISSUE THREAD

**Issue by Suzie97** [syfds/soundy#45]
# Problem
![image](https://user-images.githubusercontent.com/68198116/138641756-5309b441-035d-4b60-b0a1-9b5d18cab6fc.png)

Right now, the album does not have a drop shadow.

# Proposal
Adding a drop shadow to it, probably using `Granite.STYLE_CLASS_CARD` would make it more visually appealing and make the app feel more responsive.

# Prior Art
elementary OS Music App
![image](https://user-images.githubusercontent.com/68198116/138642132-82cb22de-5c98-4da3-942c-c79c51619010.png)

**Comment by syfds** [comment]
hi @Suzie97 , looks much better with the shadow in background, thanks for your suggestion!
![image](https://user-images.githubusercontent.com/65869270/138749874-99dd4d86-c115-4e20-b837-3f2e150f6c57.png)
