### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by elChorche** [syfds/soundy#6]
Hey there! Thanks for your work. I would really like to use this application. Unfortunately, at the moment I am only getting a segmentation fault when starting the app. 

- using version 0.1.4, installed from debian package
- up to date siduction installation on cinnamon
- SoundTouch 10 & Bose Wave Music System IV Soundtouch (same problem with both)

Starting the app and entering the IP works fine. Then the app closes. Running from terminal, connecting seems to work fine, the app grabs the 6 presets and starts downloading the radiotime logos. Then segfault. Log: 
...
** Message: 13:58:55.670: SoundtouchMessageParser.vala:240: count preset 6
** Message: 13:58:55.670: HeaderBar.vala:104: 
** Message: 13:58:55.670: HeaderBar.vala:104: http://radiotime-logos.s3.amazonaws.com/s16326q.png
** Message: 13:58:55.670: HeaderBar.vala:104: http://radiotime-logos.s3.amazonaws.com/s24862q.png
Segmentation fault

I don't know what more information I can provide, but will happily do so, if you tell me what you need.

**Comment by elChorche** [comment]
Guess I found the issue: one of my presets (the first one) is a custom url radio stream. After removing this preset and replacing it with a TuneIn station, the application is working fine. When reverting the preset: segfault. Maybe missing the containerArt tag for this preset is causing the error?

Additional terminal log:

** Message: 14:13:32.553: HttpClient.vala:47: got from soundtouch API: <?xml version="1.0" encoding="UTF-8" ?><presets><preset id="1" createdOn="1524720259" updatedOn="1618834406"><ContentItem source="LOCAL_INTERNET_RADIO" type="stationurl" location="https://content.api.bose.io/core02/svc-bmx-adapter-orion/prod/orion/station?data=eyJuYW1lIjoiS2FuYWxLIiwiaW1hZ2VVcmwiOiIiLCJzdHJlYW1VcmwiOiJodHRwOi8vMTg1LjEwMS4xNTYuMTI2In0%3D" sourceAccount="" isPresetable="true"><itemName>KanalK</itemName><containerArt></containerArt></ContentItem></preset><preset id="2" createdOn="1509706246" updatedOn="1542694601"><ContentItem source="TUNEIN" type="stationurl" location="/v1/playback/station/s16326" sourceAccount="" isPresetable="true"><itemName>Radio RaBe</itemName><containerArt>http://radiotime-logos.s3.amazonaws.com/s16326q.png</containerArt></ContentItem></preset><preset id="3" createdOn="1509706292" updatedOn="1542694601"><ContentItem source="TUNEIN" type="stationurl" location="/v1/playback/station/s103302" sourceAccount="" isPresetable="true"><itemName>SRF 3</itemName><containerArt>http://radiotime-logos.s3.amazonaws.com/s24862q.png</containerArt></ContentItem></preset><preset id="4" createdOn="1509706313" updatedOn="1542694601"><ContentItem source="TUNEIN" type="stationurl" location="/v1/playback/station/s25471" sourceAccount="" isPresetable="true"><itemName>SRF Virus</itemName><containerArt>http://radiotime-logos.s3.amazonaws.com/s25471q.png</containerArt></ContentItem></preset><preset id="5" createdOn="1509706328" updatedOn="1542694601"><ContentItem source="TUNEIN" type="stationurl" location="/v1/playback/station/s6811" sourceAccount="" isPresetable="true"><itemName>Radio 3FACH</itemName><containerArt>http://radiotime-logos.s3.amazonaws.com/s9872q.png</containerArt></ContentItem></preset><preset id="6" createdOn="1574879916" updatedOn="1602523674"><ContentItem source="TUNEIN" type="stationurl" location="/v1/playback/station/s18256" sourceAccount="" isPresetable="true"><itemName>Radio Lora</itemName><containerArt>http://cdn-radiotime-logos.tunein.com/s18256q.png</containerArt></ContentItem></preset></presets>

**Comment by syfds** [comment]
hi @elChorche , thank for creating this ticket and detailed information for this bug! I will take a look and give you feedback here ;-)

**Comment by syfds** [comment]
yeah, you are right, that was a bad handling of absent url's for a source. In such cases the app will show a default image, example: 
![image](https://user-images.githubusercontent.com/65869270/115294703-364b5500-a159-11eb-8a14-e1712ed91fe9.png)

What do you think about this approach?

**Comment by syfds** [comment]
hi @elChorche , I built a new release: https://github.com/syfds/soundy/releases/tag/v0.1.5, you can try it out and give feedback in case the bug is fixed ;-)

**Comment by elChorche** [comment]
Hey @syfds, hat was quick. Thanks a lot! The application is now working. And I like your proposed icon. However, it does not show up on my screen (see attachment). And when I change to preset 2 and back to preset 1, the image of preset 2 stays. Does not bug me, but wanted to mention it. 

![Screenshot from 2021-04-20 09-46-38](https://user-images.githubusercontent.com/82815894/115358123-a095e100-a1bd-11eb-82fd-62bcef249d3b.png)

**Comment by syfds** [comment]
hi @elChorche , yeah, presets are loaded at the startup and changes in runtime are not updated. It could be a feature request, feel free to create one! 
I guess you miss the icon because you don't have the elementary theme icon package installed on your linux mint. 

But for now I will close this ticket and create a new release for elementary app center! Thank you for creating this ticket!

Sergej
