### ISSUE TITLE
Better icon following the elementary Human Interface Guidelines Properly

### ISSUE THREAD

**Issue by Suzie97** [syfds/soundy#7]
The current icon is simple and good. That is how elementary icons should be. But there are a few tweaks that can be done to improve it. Like adding a drop shadow, refining the borders etc.

I can do it if the developer is interested.

**Comment by syfds** [comment]
hi @Suzie97 , thank you for opening this ticket! I'm interested, since I have no experience in creating icons :-) Can you make a suggestion and upload it here in this ticket? You can suggest a completely new icon too if you have a better idea how it can look. 

Do you have a SoundTouch speaker?

**Comment by Suzie97** [comment]
> hi @Suzie97 , thank you for opening this ticket! I'm interested, since I have no experience in creating icons :-) Can you make a suggestion and upload it here in this ticket? You can suggest a completely new icon too if you have a better idea how it can look.
> 
> Do you have a SoundTouch speaker?

I don't have a sound touch speaker.

**Comment by Suzie97** [comment]
I will design the icons for all the sizes and then post it here in this issue.

You can add them😊️😊️😊️

**Comment by Suzie97** [comment]
Btw, can I use the official sound touch logo? Or is Bose gonna sue the app? Let me know about the legal rules

**Comment by syfds** [comment]
hmm, I'm not sure we can use bose SoundTouch logo, so I would suggest we improve the existing one or create a new one. What do you think about it?

**Comment by Suzie97** [comment]
I'm thinking of making a mirror image of the sound touch logo. 

Like creating a pastel green cicle and then adding a sound touh inspired wifi cum music sign to it. (sorry, its hard to explain in words). I'll add the svg later today. You can check it out and propose any changes.

**Comment by Suzie97** [comment]
Hey, the 128px icon is ready. But how do you upload svg files?

**Comment by syfds** [comment]
Looks good! Is it difficult for you to create the existing icon according to elementary guidelines so we can compare them and choose one?

**Comment by Suzie97** [comment]
> 
> 
> Looks good! Is it difficult for you to adapt the existing icon according to elementary guidelines so we can compare them and choose one?

It won't be difficult. I can do it.

**Comment by Suzie97** [comment]
![Blue Soundy Logo](https://user-images.githubusercontent.com/68198116/115890487-9c461e00-a472-11eb-895e-e47a4621ef74.png)

I changed the color to blue because my girlfriend thought that it was the spotify icon. I agree. I looks too much like spotify. @syfds What do you think about blue?

Also, I removed the transperancy effect because it looks off when the background is dark.

**Comment by Suzie97** [comment]
![Soundy HIG Modified](https://user-images.githubusercontent.com/68198116/115892621-f3e58900-a474-11eb-870d-fb109e748a29.png)

This is the original logo modified according to the HIG.

**Comment by JeysonFlores** [comment]
Hey @Suzie97  That's a really great job! I would like to know what design tools or programs do you use to make those logos

**Comment by Suzie97** [comment]
I use inkscape, affinity designer and figma. All three of them. I'm used to Affinity Designer the most but sadly its not available on linux. I'll probably be switching to Inkscape although its a bit harder to use in my opinion.

**Comment by Suzie97** [comment]
> Hey @Suzie97 That's a really great job! I would like to know what design tools or programs do you use to make those icons

Thanks for your compliment.

**Comment by syfds** [comment]
hi @Suzie97 , I like the modified original logo (with white play button in the middle). Can you make a PR with the svg files in 16x16,24x24,32x32,48x48,64x64 and 128x128? Let my know if you need help!

**Comment by Suzie97** [comment]
I'll submit the PR in a few days.
